# Generated by Django 2.1.2 on 2018-12-14 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akf_app', '0002_auto_20181214_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_report',
            name='district_id',
            field=models.ForeignKey(db_column='district_id', on_delete=django.db.models.deletion.CASCADE, to='akf_app.Geo_Information'),
        ),
    ]
