# Generated by Django 2.1.2 on 2018-12-16 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akf_app', '0003_auto_20181214_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geo_information',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 16, 11, 39, 13, 974108)),
        ),
        migrations.AlterField(
            model_name='geo_information',
            name='updated_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 16, 11, 39, 13, 974108)),
        ),
        migrations.AlterField(
            model_name='student_report',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 16, 11, 39, 13, 975105)),
        ),
        migrations.AlterField(
            model_name='student_report',
            name='updated_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 16, 11, 39, 13, 975105)),
        ),
    ]
